name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --platform linux/amd64,linux/arm64 --file Dockerfile --tag ${{ vars.DOCKER_HUB_USERNAME }}/navicord:latest
      
    - name: Push the image to Docker Hub
      run: |
        docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ vars.DOCKER_HUB_USERNAME }}/navicord:latest
